### ISSUE TITLE
Make confirm button color dynamic on confirm box

### ISSUE THREAD

**Issue by ricardoduplos** [flipside-org/aw-datacollection#109]
Should be possible to set the color through data attributes.

**Comment by danielfdsilva** [comment]
Data attributes to change bttn color:

```
data-confirm-accept-skin="<class_name>"
data-confirm-cancel-skin="<class_name>"
```

Possible classes:
- bttn-default (Default for cancel btn)
- bttn-success (Default for accept btn)
- bttn-danger
- bttn-primary

When the data attribute is not set default values are used.
