### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by nunoveloso** [flipside-org/aw-datacollection#14]
Add some logging throughout the code, for critical operation:
- success / info / status / notice
- warning
  -failure / error

This should be able to be controlled enabled at the following levels:
- all: saves all logs
- no-notices: only warnings and errors
- errors-only
- none

**Comment by danielfdsilva** [comment]
@nunoveloso 
CI has a log_message('level', 'message') function but you cannot control what to log.
Would it be useful to build a proper logging class, or we just stick to this?

**Comment by danielfdsilva** [comment]
Using CI function
