### ISSUE TITLE
Debug why sendmail isn't working

### ISSUE THREAD

**Issue by nunoveloso** [flipside-org/aw-datacollection#31]
Vagrant box didn't have the required OS packages and configs for this. Not sure if it solves the code igniter part of it, but we can now send emails via OS.

Steps to be replicated vagrant config:

```
$ sudo apt-get install coreutils mailutils sendmail 
$ sudo sendmailconfig
```

Test with:

```
$ echo "This will go into the body of the mail." | mail -s "Hello world" nuno@flipside.org
```

**Comment by danielfdsilva** [comment]
I setup the vagrant box from scratch and ran those commands but the email was not sent.
Ideas?

**Comment by nunoveloso** [comment]
@danielfdsilva working now?
